2-guys-Javascript/travel-web-app

- src/App.jsx
- src/components/Home/Home.css
- src/components/Home/Home.jsx
- src/components/Japan/Exchange.jsx
- src/components/Japan/JpLayout.jsx
- src/components/Japan/JpNavBar.jsx
- src/components/Japan/JpWeather.jsx
- src/components/Korea/KrLayout.jsx
- src/components/Korea/KrNavBar.jsx
- src/components/Korea/KrWeather.jsx
- src/main.jsx
일단 지금 저희가 구상했던 화면에서 필요해보이는 라우팅 설정은 모두 마쳤는데요,
앞으로 계속 추가적인 리팩토링은 필요하긴 할 것 같습니다. (수준미달 이슈)
export 관련 업데이트해서 pr 올립니다!
> Feat: 라우팅 관련 설정 끝냈습니다!

- src/App.jsx
- src/components/Home/Home.jsx
- src/components/Japan/JpDefaultLayout.jsx
- src/components/Japan/JpNavBar.jsx
- src/components/Korea/KrDefaultLayout.jsx
- src/components/Korea/KrNavBar.jsx
> Layout name을 CountryDefaultLayout으로 변경함에 따른 변화입니다

- .gitignore
> 🛠️CHORE: 깃이그노어 파일 수정했습니다!

- package-lock.json
- package.json
- src/components/Japan/Exchange.jsx
- src/components/Japan/JapanDefaultLayout.css
- src/components/Japan/JpNavBar.jsx
- src/setupProxy.js
변경 사항은 다음과 같습니다
1. exchange.jsx 파일에서 api를 끌어다가 컴포넌트를 만들었습니다. 해당 api키는 노션에 공유하겠습니다.
2. JpNavBar 컴포넌트가 바뀌었습니다. 해당 컴포넌트의 header에 클래스를 부여하고 margin bottom과 padding bottom을 주었습니다.
3. 특정 url로 api를 통해 환율 데이터를 받아오려고 하니 CORS 문제에 직면했습니다. 이를 해결하기 위해 http-proxy-middleware 모듈을 설치했습니다. 모듈을 설치한 뒤 해당 설정은 setupProxy.js 파일에서 해주었습니다.
혹시나 궁금하신 점 있으시면 언제든지 질문 주시면 감사하겠습니다!
> 환율 컴포넌트 작성에 대한 pr입니다 확인하시고 merge 부탁드려요

- src/components/Japan/JapanDefaultLayout.css
- src/components/Japan/JpWeather/JpHourlyWeather.jsx
- src/components/Korea/KoreaDefaultLayout.css
- src/index.css
> 🎨STYLE: 모바일 환경 맞춤 디자인 수정

- src/components/Japan/JapanDefaultLayout.css
- src/components/Japan/JpWeather/JpHourlyWeather.jsx
- src/components/Korea/KrWeather/KrHourlyWeather.jsx
> ⚙️REFACTOR: list 태그 키값 부여 + 약간의 코드 수정

- firebaseConfig.js
- package-lock.json
- package.json
파이어 베이스 파이어 스토어 연결 읽기 쓰기 확인까지 마쳤습니다!
> 🛠️CHORE: firebase 환경 세팅

- package-lock.json
- package.json
- src/components/Japan/Exchange.jsx
- src/components/Japan/JpWeather/JpWeather.jsx
- src/components/Korea/KrWeather/KrWeather.jsx
1. exchange, weather 관련 컴포넌트들에 있던 불필요한 주석을 제거해 주었습니다.
2. `http - proxy - middleware` 모듈을 package.json의 dependencies에서 devdepencies로 이동시켜주었습니다.
=> `npm install http - proxy - middleware -D` 명령어
웹 애플리케이션의 작동은 이전과 다른 것은 없습니다. 다만 devdependencies에 들어가는 모듈들은 배포 시에 제외되는 것으로 알고 있는데, 배포시 문제가 생기면 해결해주는 그림이 펼쳐질 수도 있을듯...
> Comment: delete unnecessary comment in jsx file and change node_modules

- src/components/Japan/JpWeather/JpWeather.jsx
- src/components/Korea/KrWeather/KrWeather.jsx
- src/index.css
영어로 출력 되던 게 영 불편했는데, weatherAPI 공식 문서를 보니까 언어 설정을 따로 해줄 수 있더라구요(condition:text 부분만 가능함..)
그래서 언어를 한글로 바꿔줬습니다! 보이는 것처럼 한글로 출력됩니다.
영어로 출력될 때랑 한글로 출력될 때랑 문자의 크기 차이는 없는데, 체감되는 느낌은 많이 다르더라구요 (한글이 짧고 뚱뚱해보임)
그래서 자연스러운 느낌을 주려고 마진값을 18px > 35px로 수정했습니다!
> ✨FEAT : Current Day 날씨 정보(text) 영어 > 한글로 출력

- package-lock.json
- package.json
- src/components/Japan/Japan.jsx
- src/components/Maps/NonLoginMap.jsx
> Feat: add non-login map by using reac/google-map-api

- src/components/Maps/CreateMarkerForm.jsx
- src/components/Maps/LoginMap.jsx
- src/components/Maps/Map.css
- src/components/Maps/MarkerInfo.jsx
- src/components/Maps/NonLoginMap.jsx
임의의 center 값을 줬었는데, 이제는 앱을 실행하면 일정 시간이 지난 후에 현재의 위치를 받아오도록 수정하였습니다!
결과를 받아오기 전까지의 임의의 position 값은 서울 어딘가로 잡았습니다... 😅
이 전에 클릭하면 마커를 생성하는 것까지 구현 했었는데, 생성한 마커에 커스텀 가능한 객체값을 넣을 수 있도록 기능을 추가하였습니다.
그 과정에서 마커 일정을 생성하는 중에 여백에 맵안의 다른 부분을 클릭 했을 때 오류가 뜨던 것과, 이 전에 기록해둔 일정을 클릭 했을 때 마커가 아무런 정보 없이 찍히던 것, 마커 생성 중 다른 마커의 정보를 봤다가 생성중이던 마커를 눌렀을 때 생기는 오류 등 대부분의 에러는 해결했습니다.
나중에 발견하고 해결 못한 에러로 마커 생성 중, 생성 중인 마커를 클릭 했을 때 생기는 오류만 해결하면 될 것 같습니다!
마커에 등록된 일정을 읽을 수 있는 기능을 구현하였습니다! 
마커에 등록된 내용은 marker.info 객체값 안에 넣어두었고 나중에 db랑 연결하려고 할때 헷갈리지 않도록 console.log는 지우지 않고 남겨놨습니다..! 내일 아마 확인 하시기에도 수월할 것 같습니다! 👍
여기서도 해결되지 못한 여러가지 문제점이 존재합니다.
아마 찾지 못한 버그도 여럿 있을 수 있습니다..,, 켁 🙇🏻‍♂️🙇🏻‍♂️🙇🏻‍♂️
생각보다 기능을 구현하는데 시간을 많이 소비해 유효성 검사까진 진행하지 못했습니다...!
현재는 아무런 내용을 넣지않고 생성하게 되더라도 마커가 찍힙니다..! 하지만 이 부분은 수정해야겠습니다!
추가로 일정에 시간 단위도 1시간이나 30분 간격으로 …
> ✨FEAT : 현재 위치 표시 + 마커에 일정 기록 기능 추가

- package-lock.json
- package.json
- src/components/Japan/Japan.jsx
- src/components/Korea/Korea.jsx
- src/components/Maps/CreateMarkerForm.jsx
- src/components/Maps/LoginMap.jsx
- src/components/Maps/Map.css
- src/components/Maps/MarkerInfo.jsx
- src/components/Maps/NonLoginMap.jsx
생성중이던 마커를 클릭할 때 발생하던 오류에 대해서 해결 하였습니다.
form 태그를 활용하고 불필요한 코드를 줄이는 방면으로 리팩토링 하였습니다.
상황에 맞는 컴포넌트 명으로 수정하였습니다.
추가적으로 Japan 컴포넌트에서만 출력되던 지도 화면을 한국 화면에서도 출력 될 수 있도록 수정하였습니다.
간단한 기능을 구현하는데 유용한 패키지를 사용하여 생산성을 높이고, 불필요 했던 코드의 복잡성을 해결했습니다.
> 유효성 검사를 구현해야 합니다.
> CreateMarkerForm의 UX를 고려해 수정해야합니다.
> MarkerInfo의 UI를 수정 해야합니다.
> 로그인 상태에 따른 지도 출력을 구현해야 합니다.
> 데이터 베이스와 marker의 정보가 연결되어야 합니다.
> NonLogin 화면에서 출력될 화면에 주변 정보 데이터를 받아와야 합니다. (google place || trip advisor API)
> ⚙️REFACTOR: 리팩토링 중

- src/components/Maps/CreateMarkerForm.jsx
- src/components/Maps/Map.css
> ✨FEAT: 함께했어요. 내용 설명 X

- src/components/Maps/LoginMap.jsx
- src/components/Maps/NonLoginMap.css
- src/components/Maps/NonLoginMap.jsx
- src/components/Maps/PlaceInfo.jsx
Google Place API를 활용하여 검색 기능과 마커를 추가하는 기능을 구현했습니다.
검색한 주변 반경 500m에 평점 높은 순으로 최대 20개의 음식점과 카페를 출력하도록 설정하였습니다.
검색한 결과를 클릭하면 열렸는지 닫혔는지에 대한 정보와 주소가 담겨있습니다!
더 많은 정보를 받아올 수 있었다면 이쁘게 하고 싶은 욕심도 있었는데, 시간이 너무 오래걸릴까봐 멈췄습니다 일단,, 🙂
현재 위치로 이동하는 버튼을 추가하였습니다.
현재 위치에도 마커가 표시되며 추후에 마커 아이콘을 수정하는 식으로 구분 해줄 수도 있을 것 같습니다!
position: fixed 를 적극적으로 활용해서 스크롤 이벤트가 발생할 때마다 맵이 사라지던 불편함을 없앴습니다.
또한 지도에 관한 기능들은 지도와 함께 포지션을 고정해줬습니다!
> ✨FEAT: 비로그인 컴포넌트 구현 90% 완료 + 스타일링

- src/components/App-Header/ApplicationHeader.jsx
- src/components/App-Header/applicationHeader.css
- src/components/Maps/LoginMap.css
- src/components/Maps/LoginMap.jsx
- src/components/Maps/Map.css
- src/components/Maps/NonLoginMap.css
- src/components/Maps/NonLoginMap.jsx
> - 생성중인 마커를 클릭 했을 때, 주변 정보를 받아오던 버그를 수정하였습니다.
> - 마커를 클릭했을 때만 마커 주변의 정보를 받아오도록 수정하였습니다.
마커로 저장된 일정 정보를 리스트화 해서 지도 하단에 출력하는 기능을 추가하였습니다!
아직 간단하게만 구현을 해놓은 상태이고 추가적인 기능을 구현할 예정입니다.
ex) 리스트를 클릭하면 클릭한 일정 마커로 위치로 이동 + 일정 주변 정보 표시
--- | --- | 
곂치는 CSS 코드는 class를 다시 지정해주고, 기존 코드를 최대한 줄이는 방식으로 구현하였습니다.
추가적으로 date type input의 스타일이 너무 구려서,, text 타입으로 덮어씌워 스타일을 주었고 실제 기능은 date가 하도록 했습니다!
이 부분마저도 구려 나중에 여유가 된다면 수정 해볼까 합니다!
--- 
오늘 집에 일이 좀 있어서 코드를 만질 시간이 적었습니다..ㅠㅠ
새벽에 더 추가적인 기능을 구현할 생각이라 PR 올려주시면 올려주시는대로 진행 하겠습니다!!
또 추가적으로 궁금하시거나 필요한 구현 사항을 말씀해주시면 바로 반영하겠습니다!
> 🐞FIX: 자잘한 버그들 수정 + CSS 코드 리팩토링

- src/components/Maps/CreateMarkerForm.jsx
- src/components/Maps/LoginMap.css
- src/components/Maps/LoginMap.jsx
- src/components/Maps/MarkerInfo.jsx
일부 버그를 수정하고, 기능을 구현하여 PR 남깁니다.
1. 동준님과 카톡으로 말씀드렸던 특정 일정을 생성하던 도중(완성하지 않고), 다른 장소를 검색하여 이동할 때 기존의 마커가 계속해서 남아있고 새로운 일정을 생성해도 두 마커가 생기는 현상을 해결했습니다. `LoginMap` 컴포넌트의 `handleSearch` 함수에 조건을 걸어주어 해결했습니다!
```javascript
if (!isMarkerExist) {
const newMarker = {
id: newCenter.lat,
position: newCenter,
};
if (creatingMarker) {
setMarkers([...markers.slice(0, markers.length - 1), newMarker]);
} else {
setCreatingMarker(true);
setMarkers([...markers, newMarker]);
}
``` 
2. 삭제 기능을 구현했습니다. `MarkerInfo` 컴포넌트에서 삭제 버튼을 생성해주었습니다. 로직은 보시면 쉽게 이해가 가실 것 같습니다.
3. 지난 번에 저희가 얘기 나눴던 generateTimeButtons() 함수를 함수 실행 방식으로 전달하지 않고, 컴포넌트로 만들어서 JSX 코드 안에 넣어주었습니다. 
4. 기존에 로그인 맵에 들어가면, 상관 없는 장소로 렌더링이 됐었는데 그냥 `userLocation` 상태값을 빼버리니, 그런 의도치 않은 효과를 없앨 수 있었습니다 :)
5. `MarkerInfo`  컴포넌트로 전달되는 prop 명이 좀 애매한 것 같아 marker에서 …
> Seungwan fork

- src/components/App-Header/ApplicationHeader.jsx
- src/components/App-Header/applicationHeader.css
- src/components/Home/Home.css
- src/components/Home/Home.jsx
- src/components/Japan/Exchange.jsx
- src/components/Japan/Japan.jsx
- src/components/Japan/JpNavBar.jsx
- src/components/Japan/JpWeather/JpForecastWeather.jsx
- src/components/Japan/JpWeather/JpHourlyWeather.jsx
- src/components/Japan/JpWeather/JpWeather.jsx
- src/components/Korea/Korea.jsx
- src/components/Korea/KoreaDefaultLayout.css
- src/components/Korea/KrNavBar.jsx
- src/components/Korea/KrWeather/KrWeather.jsx
- src/components/Login/Login.jsx
- src/components/Login/LoginForm.jsx
- src/components/Login/login.css
- src/components/Maps/CreateMarkerForm.jsx
- src/components/Maps/LoginMap.jsx
- src/components/Maps/MarkerInfo.jsx
- src/components/Maps/NonLoginMap.jsx
- src/components/SignUp/SignUpForm.jsx
1. 불필요한 주석과 쓰이지 않는데 존재하는 prop을 지워줬습니다. 나중에 추가적인 기능 구현을 할 때 필요하다면 그때 다시 적어줘도 될 것 같습니다.
2. 애플리케이션 헤더에 있는 일단락을 누르면 커서가 포인터로 바뀌고, home으로 이동할 수 있게 만들어 줬습니다. `Link` 컴포넌트로 h2 태그를 감싸주어 구현할까 시도해봤지만 그러면 기존의 css와 충돌이 나서, 그냥 `useNavigate` 훅을 사용한 핸들러 함수를 `onClick` 속성으로 걸어주었습니다.
> ⚙️Refactor : 불필요한 주석 제거 & 일단락 버튼 클릭시 홈페이지로 이동

- src/App.jsx
- src/components/App-Header/ApplicationHeader.jsx
- src/components/App-Header/applicationHeader.css
- src/components/Login/Login.jsx
- src/components/Login/LoginForm.jsx
- src/components/MyPage/MyPage.jsx
- src/components/MyPage/Mypage.css
동영상은 길이가 약간 길어 동준님 개인 카톡으로 보내드렸습니다! 작성 코드의 주요 포인트는 다음과 같습니다.
1. Application Header에 마이페이지로 갈 수 있는 버튼을 하나 만들어 줬습니다. 당연한 것이지만, 로그인한 사용자의 헤더에만 해당 버튼이 나타나야 하므로 `isLoggedIn` 상태가 true이어야만 해당 버튼이 나타나도록 만들어 줬습니다. 참고로 해당 버튼은 fixed라서 flex 박스인 애플리케이션 헤더에 영향을 받지 않도록 해줬습니다. [관련 코드](https://github.com/Programming-Seungwan/travel-web-app_fork_seungwan/blob/ec1e9fdaad10dedccf462564228ceb2b6da57178/src/components/App-Header/ApplicationHeader.jsx#L35-L38)
2. 마이페이지 화면은 `MyPage` 컴포넌트를 만들어줌으로써 구현했고, 이는 `App.jsx`에서의 라우팅도 잘 처리해주었습니다. 그런데, 마이페이지의 폼에서 나타나는 displayName은 App 컴포넌트로부터 prop으로 받은 displayName 상태를 쓰면 안됩니다. 그 방식을 따르면 사용자가 input 태그에 양방향으로 바인딩된 값을 바꿀 때마다, ApplicationHeader에 있는 닉네임도 계속해서 함께 바뀌는 기괴한 현상이 일어납니다.
따라서 `myPageDisplayName`이라는 상태를 해당 컴포넌트에서 만들어주고, 컴포넌트가 처음 로드될 때 로컬 스토리지에 저장된 displayName을 받아오도록 …
> ✨Feat : my page 기능 구현

- src/components/Maps/LoginMap.css
- src/components/Maps/LoginMap.jsx
- src/components/MyPage/MyPage.jsx
- src/components/MyPage/Mypage.css
- src/components/SignUp/signup.css
별다른 큰 수정사항 없습니다! 
main 디렉토리에 합치도록 하겠습니다..!
> ✨FEAT: 깃허브 로그인 시 닉네임 변경 불가능하게 수정

- src/components/Maps/LoginMap.css
날짜를 선택하는 버튼이 상단에 항상 고정되어 있도록 추가하였습니다!
> 🎨STYLE: react-datepicker > position:sticky 줬습니다!

- src/components/Maps/LoginMap.css
- src/components/Maps/LoginMap.jsx
익숙하지 않은 사용자로 하여금 지도 하단에 변화가 눈에 들어오지 않을 수 있을 것 같습니다.
그래서 큰 변화를 주기보단 살짝 지도 하단에 공간에 변화가 있다는 걸 표현해주기 위해서 살짝 위(150px)로 올라오도록 기능을 수정하였습니다!
오늘 새벽 중으로 실제 배포 환경에 적용 하도록 하겠습니다 여행 즐겁게 즐기다 오세요!!! ✈️🇯🇵☃️
실제로 조작 가능한 클래스명이 react-datepicker가 아닌 react-datepicker-wrapper라는 것을 뒤늦게 확인하고 적용합니다...!
+ open 클래스가 적용된 상태에서는 또 화면 하단이 위로 올라가서 안보이네요 ㅋㅋㅋㅋ ㅠㅠ 크게 문제될 것 같지는 않습니다!
> ✨FEAT: 자연스러운 UX 움직임 추가

- src/components/Maps/LoginMap.css
- src/components/Maps/LoginMap.jsx
- src/components/Maps/Map.css
- src/index.css
기존 코드에서 약간의 픽셀 수정 정도만 있습니다!
추가적으로 항상 최상단에 올라와 있도록 z-index 값을 100을 주었고,
기존에 root가 정상적으로 화면을 덮고 있지 못했던 점을 발견해 수정했습니다.
+ 오늘 중으로 전체일정 부분을 추가하도록 하겠습니다!
> 🐞FIX: DatePicker가 제대로 화면에 표시되지 않던 오류를 해결했습니다.

- src/components/Maps/LoginMap.css
내일부터 다시 리팩토링 + 기능 추가 진행하면서 기획하도록 하겠습니다!
> 🐞FIX: 첫 렌더링 시 일정 리스트 상단에 date picker가 고정되지 않는 버그 수정
